image:  selenium/standalone-chrome:4.14.0-20231107 # Asigură-te că utilizezi cea mai recentă versiune


build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - mvn clean compile # Compilează codul sursă folosind Maven

test-job1:
  stage: test
  script:
    - echo "Running quick tests"
    - mvn test -Dtest=org.example.TestNavBar # Rulează testele specifice definite în TestNG

test-job2:
  stage: test
  script:
    - echo "Running comprehensive tests"
    - mvn test # Rulează toate testele

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying to production from the $CI_COMMIT_BRANCH branch"
  environment: production
